### ISSUE TITLE
Feature: Support mocks inheriting from classes

### ISSUE THREAD

**Issue by seanhenry** [seanhenry/MockGenerator#11]
# AppCode mock generator class support.
Please leave a comment if you are interested in this feature.
## Tasks
- [x] Support 1 superclass
- [x] Ignore structs
- [x] Ignore constants
- [x] Ignore static methods/properties
- [x] Ignore methods in lower scope (internal only)
- [x] Ignore final classes and methods
- [x] Recognise type inferred properties
### Hierarchy
- [x] Support super superclasses
- [x] Ignore NSObject
- [x] Support mixed inherited class and protocols
### Initialiser
- [x] Support initialiser with arguments
- [x] Call descendant initialiser with default arguments where possible.
- [x] Ignore private and file-private initialisers
- [x] Support multiple initialisers
- [x] Support required initialisers 
- [x] Support convenience initialisers
- [x] Support failable initialisers
### Generic
- [ ] Support for generic classes
### Scope
- [x] Support public/open/internal
- [ ] Support open in 3rd party
### Class structure
- [x] Support lazy properties
- [x] Support implicit type properties set by methods
- [x] Support implicit type properties set by properties
- [x] Support implicit type properties set by constructor
- [x] Support implicit type properties set by literal
- [ ] Support class methods/properties
- [x] Support computed properties
- [x] Support private(set), internal(set), fileprivate(set)
### Extensions
- [x] Ignore class extensions (cannot yet be overridden)

**Comment by dnedrow** [comment]
This would be really handy for use in our code base, as our architecture is protocol "resistant". ;) 
Virtually everything that needs mocked are concrete classes.

**Comment by amseddi** [comment]
👍 This would be useful to avoid creating unnecessary protocols that are used just for mocking.

**Comment by seanhenry** [comment]
Thanks both. I'll look into to this shortly. Stay tuned!

**Comment by seanhenry** [comment]
@amseddi @dnedrow @alexandre-g

The first beta release is ready in the [releases](https://github.com/seanhenry/MockGenerator/releases) page. Post any feedback you have here.

Happy mocking!

**Comment by seanhenry** [comment]
Initializer support is [here](https://github.com/seanhenry/MockGenerator/releases/tag/v8.beta.4)!

- Ignores private and fileprivate initializers.
- Generates a convenience initializer for class mocks when needed.
- Calls the most simple initializer from the convenience initializer.

The idea behind this is that you should not need any dependencies to create mocks. For example:
```
class MyClass {
  init(a: String) {}
}

class MyClassMock: MyClass {
  convenience init() {
    self.init(a: "")
  }
```

**Comment by seanhenry** [comment]
I have submitted a new plugin with class support. You can find it on [here](https://github.com/seanhenry/MockGenerator/releases) or it will appear as an update in AppCode soon.
